# IMPORTANT!
# Requested - Ensure the environment is entirely ephemeral
services:
  gitlab:
      image: gitlab/gitlab-ce:latest
      ports:
        - 80:80
        - 443:443
        - 22:22
  jenkins:
      image: jenkins/jenkins:lts
      ports:
        - 8080:8080
      environment:
        - JENKINS_OPTS=--prefix=/jenkins
