---
- name: Deploy NGINX Container Using Ansible
  hosts: all
  become: yes
  tasks:
    - name: Update The System
      apt:
        update_cache: yes
      become: yes

    - name: Prerequisites Packages Installation
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add The GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add The Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: yes

    - name: Docker Installation
      apt:
        name: docker-ce
        state: present
      become: yes

    - name: Docker service Start
      service:
        name: docker
        state: started
      become: yes

    - name: Pull The Latest NGINX Docker image
      docker_image:
        name: ortoledanoo/weather-app
        tag: latest
        source: pull
      become: yes

    - name: Run NGINX Container
      docker_container:
        name: weatherapp_container
        image: ortoledanoo/weather-app
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
      become: yes
