---
- name: Deploy Weather-App Container Using Ansible
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - docker-ce
        state: present
        update_cache: yes

    - name: Add Docker GPG Key and Repository
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

    - name: Ensure Docker Service Is Running
      service:
        name: docker
        state: started

    - name: Deploy Weather App Container
      docker_container:
        name: weatherapp_container
        image: ortoledanoo/weather-app:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
