services:
  nginx:
    image: do21-lab-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./cert.crt:/etc/nginx/ssl/cert.crt
      - ./cert.key:/etc/nginx/ssl/cert.key
      - ./default.conf:/etc/nginx/conf.d/default.conf
