apiVersion: v1
kind: Service
metadata:
  name: solitaire-app-service
  labels:
    app: solitaire-app
spec:
  type: NodePort
  selector:
    app: solitaire-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007