apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  labels:
    app: weather-app
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000 
    nodePort: 30007  

# Definition

# port: The port that the Service listens internally (80).
            # Used by other Pods within the cluster to access the Service.

# targetPort: The port inside the Pod where the application is running (5000).
            #  Must match the gunicorn listening port.

# nodePort: The port on the Node’s IP that exposes the Service globally (30007).
            # Used for accessing the app from outside the cluster.


### Flow Node Port

# 1. A client sends a request to the Node's public IP on the nodePort (http://My-Public-IP:30007).
# 2. The NodePort forwards the request to the Service's ClusterIP (80).
# 3. The Service uses the ClusterIP to route the request to one of the backend Pods.
# 4. The Service forwards the request to the targetPort (5000) on the selected Pod of the weather-app.

