services:
  app_container:
    image: ortoledanoo/weather-app
    volumes:
      - ./weather_app.log:/app/weather_app.log
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  # Filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.1
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./weather_app.log:/usr/share/filebeat/logs/weather_app.log:ro
    command: ["filebeat", "-e", "-strict.perms=false"]
    environment:
      - ELASTICSEARCH_HOST=51.17.64.59
      - ELASTICSEARCH_PORT=9200
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

