filebeat.inputs:
  - type: log
    paths:
      - /usr/share/filebeat/logs/weather_app.log
    multiline.pattern: '^(INFO|ERROR|DEBUG):'
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ['10.0.0.6:5044']
  protocol: "1"
