services:
  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    ports:
      - "9200:9200" # Open Port for HTTP With ES
      - "9300:9300" # Open port for Internal Communication inside Cluster
    volumes:
      - es_data:/usr/share/elasticsearch/data/
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node # Run as Single Node (No Need To Find Another Nodes)
      - http.host=0.0.0.0 # Set ES To Listen All IP's
      - transport.host=0.0.0.0 # ?
      - xpack.security.enabled=false # Disable The ES Default Security Mechanism (To Simplify)
      - xpack.monitoring.enabled=false # Disable The Kibana Monitoring To Reducce Resource Usage
      - cluster.name=elasticsearch # Set Cluster Name
      - bootstrap.memory_lock=true # Enble "Memory Lock" To disable the 'memory swap' on this ES Procceses
    networks:
      - elk

  logstash:
    image: logstash:7.9.1
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ls_data:/usr/share/logstash/data
      - ./elk-config/logstash/ca-cert.pem:/usr/share/logstash/ca-cert.pem
      - ./elk-config/logstash/server.crt:/usr/share/logstash/server.crt
      - ./elk-config/logstash/server.key:/usr/share/logstash/server.key

    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  es_data:
  ls_data:
  kb_data:
